export const APP_DRAWER_TOGGLE = 'APP_DRAWER_TOGGLE';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_ANSWER_TO_QUESTION = 'ADD_ANSWER_TO_QUESTION';
export const DELETE_ANSWER_TO_QUESTION = 'DELETE_ANSWER_TO_QUESTION';
