export const APP_DRAWER_TOGGLE = 'APP_DRAWER_TOGGLE';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const RECEIVE_ANSWERS = 'RECEIVE_ANSWERS';
export const TOGGLE_ANSWER_TO_QUESTION = 'TOGGLE_ANSWER_TO_QUESTION';
